### ISSUE TITLE
请教一个关于视频抽帧的问题

### ISSUE THREAD

**Issue by xinyeCH** [Tencent/CenseoQoE#1]
每个视频因为运动信息强弱，不同帧可能会有不同的质量，如果像Konvid这种单个打分的视频数据集，对视频帧都赋予同一个打分是不是不合理？请教下这个问题是否有解决办法。

**Comment by shaoguowen** [comment]
Konvid应该是对一个视频的整体评分吧？不是每一帧的分数。在训练模型的时候，通过对每一帧预测的分数做平均或是使用RNN网络额外捕捉时序上信息 从而获得该视频整体的质量分数，所以没有不合理，也符合ITU的标准。对于大部分正常的视频来说，虽然每一帧有好有坏，但质量分数应该不会差异过大，当然不排除一些极端的视频，比如通过转场将很好和很差的视频拼接起来，这样预测的分数确实会有影响，所以我们在构建视频的画质评价数据集的时候，不会加入这种类型的视频做主观打分。当然如果为了对每一帧做更精确的评分，可以考虑构建一个针对图像的画质评价数据集，然后针对图像训练模型

**Comment by xinyeCH** [comment]
好的，谢谢你的解答。
