### ISSUE TITLE
Is DMOS value necessary?

### ISSUE THREAD

**Issue by Cassieyy** [Tencent/CenseoQoE#10]
Hi shaoguo, thanks for ur great job!!! 
    Now, i have the MOS value of images but not DMOS, could i use this repo for IQA trainning? I wanna know if the DMOS value is necessary in trainning model.  Looking forward to ur reply and thanks in advance!!!

**Comment by shaoguowen** [comment]
DMOS is not necessary, which is a placeholder for another training task. You can train your own model only with MOS value.

**Comment by Cassieyy** [comment]
您的邮件已收到哦我会及时处理哒~
