### ISSUE TITLE
English

### ISSUE THREAD

**Issue by bhargav-sudo** [Tencent/CenseoQoE#11]
Hi, It would help me if this page is in English language.
Sorry, 

Thanks.

**Comment by shaoguowen** [comment]
Sorry to reply you so late, the English version of README has been updated. Please refer to: https://github.com/Tencent/CenseoQoE/blob/master/README_EN.md 
https://github.com/Tencent/CenseoQoE/blob/master/CenseoQoE-SDK/README_EN.md
https://github.com/Tencent/CenseoQoE/blob/master/CenseoQoE-Algorithm/README_EN.md
