### ISSUE TITLE
为什么识别过程这么慢呢？能不能创建个群，有很多疑问；

### ISSUE THREAD

**Issue by skyline205** [Tencent/CenseoQoE#2]
![image](https://user-images.githubusercontent.com/66421783/143795996-cb83f0e7-d1ab-4b92-8842-ae32334e3fe7.png)

**Comment by shaoguowen** [comment]
现在SDK使用cpu版本的libtorch运行的，你是在MAC上运行的吗？MAC有个bug现在只能调用单个CPU核，这个bug我有时间定位一下，在linux上可以使用多个cpu，速度会快很多。后续我会加上GPU版本的libtorch支持，如果急着用并且有GPU的话，可以考虑用 https://github.com/Tencent/CenseoQoE/tree/master/CenseoQoE-Algorithm/test_code 运行哈，模型是一样的。
![censeo](https://user-images.githubusercontent.com/57278682/144026496-125fea5f-9157-4b92-85c0-2940aab60830.jpg)

**Comment by shenguquanxin** [comment]
二维码过期啦，能重新搞一个嘛
