### ISSUE TITLE
tensorflow GPU版本似乎有问题，一运行就报错

### ISSUE THREAD

**Issue by quliulangle** [Tencent/CenseoQoE#5]
如题

**Comment by shaoguowen** [comment]
报什么错，可以把log发一下么？

**Comment by quliulangle** [comment]
> 报什么错，可以把log发一下么？

tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node convolution}}]]
	 [[test_output/_5]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node convolution}}]]
0 successful operations.
0 derived errors ignored.

**Comment by shaoguowen** [comment]
你用的tensorflow版本是1.15吗？

**Comment by shaoguowen** [comment]
没有回复，先关闭了
