### ISSUE TITLE
可否提供一下ugc模型训练数据的下载链接

### ISSUE THREAD

**Issue by wzqgepoge** [Tencent/CenseoQoE#7]
模型效果符合预期，想在ugc模型里添加自己的标注数据，但数据量较少。作者可否提供一下ugc模型训练练数据或下载链接，多谢。

**Comment by wzqgepoge** [comment]
忘了说  是无参考模型的图片训练集，模型用于iqa

**Comment by shaoguowen** [comment]
hi，不好意思，使用的数据是内部自研的数据集，暂时不打算公开。可以考虑自己标注一批数据集哈

**Comment by wzqgepoge** [comment]
好的  多谢回复
