### ISSUE TITLE
mac M1笔记本上编译不过

### ISSUE THREAD

**Issue by chencuber** [Tencent/CenseoQoE#9]

**Comment by chencuber** [comment]
补充：
看起来是下载libtorch c++库不支持arm，我尝试使用brew install libtorch安装的libtorch，但有下面的错误：
<img width="793" alt="image" src="https://user-images.githubusercontent.com/34364618/170026100-2d4ad7cf-96c0-46e1-b52e-0908d4c09421.png">


ld: library not found for -lmkl_intel_ilp64，是不是哪个三方库的用了mkl？
<img width="690" alt="image" src="https://user-images.githubusercontent.com/34364618/170022265-d17a1df5-17eb-4204-877e-1d1fbafffafc.png">

**Comment by shaoguowen** [comment]
m1没试过，估计有一些库还没有支持m1的芯片
